### ISSUE TITLE
App Crashes When Select Contact

### ISSUE THREAD

**Issue by legaciespanda** [jayeshpansheriya/flutter_native_contact_picker#7]
I got the following error when i selected contact from my android device and the app crashes

E/AndroidRuntime(12753): FATAL EXCEPTION: main
E/AndroidRuntime(12753): Process: com.hey.kingo, PID: 12753
E/AndroidRuntime(12753): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2015, result=-1, data=Intent { dat=content://com.android.contacts/data/3885 flg=0x1 }} to activity {com.finapp.payworth/com.hey.kingo.MainActivity}: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
E/AndroidRuntime(12753): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5324)
E/AndroidRuntime(12753): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5365)
E/AndroidRuntime(12753): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(12753): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(12753): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(12753): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2197)
E/AndroidRuntime(12753): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(12753): 	at android.os.Looper.loop(Looper.java:268)
E/AndroidRuntime(12753): 	at android.app.ActivityThread.main(ActivityThread.java:8016)
E/AndroidRuntime(12753): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12753): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
E/AndroidRuntime(12753): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
E/AndroidRuntime(12753): Caused by: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
E/AndroidRuntime(12753): 	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:514)
E/AndroidRuntime(12753): 	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:138)
E/AndroidRuntime(12753): 	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:52)
E/AndroidRuntime(12753): 	at android.database.CursorWrapper.getString(CursorWrapper.java:141)
E/AndroidRuntime(12753): 	at com.jayesh.flutter_contact_picker.FlutterContactPickerPlugin.onActivityResult(FlutterContactPickerPlugin.kt:104)
E/AndroidRuntime(12753): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:807)
E/AndroidRuntime(12753): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:430)
E/AndroidRuntime(12753): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:811)
E/AndroidRuntime(12753): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:771)
E/AndroidRuntime(12753): 	at android.app.Activity.dispatchActivityResult(Activity.java:8408)
E/AndroidRuntime(12753): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5317)
E/AndroidRuntime(12753): 	... 11 more
I/ExceptionHandle(12753): at android.app.ActivityThread.deliverResults(ActivityThread.java:5324)
I/ExceptionHandle(12753): at android.app.ActivityThread.handleSendResult(ActivityThread.java:5365)
I/ExceptionHandle(12753): at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
I/ExceptionHandle(12753): at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
I/ExceptionHandle(12753): at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
I/ExceptionHandle(12753): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2197)
I/ExceptionHandle(12753): at android.os.Handler.dispatchMessage(Handler.java:106)
I/ExceptionHandle(12753): at android.os.Looper.loop(Looper.java:268)
I/ExceptionHandle(12753): at android.app.ActivityThread.main(ActivityThread.java:8016)
I/ExceptionHandle(12753): at java.lang.reflect.Method.invoke(Native Method)
I/ExceptionHandle(12753): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
I/ExceptionHandle(12753): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
I/flutter (12753): data

**Comment by minhx3** [comment]
me too, i get same issue

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.4, on macOS 14.2 23C64 darwin-x64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.85.1)
[✓] Connected device (2 available)
[✓] Network resources

**Comment by darmanovazamat** [comment]
Same. Experienced this on Redmi Note 8 (MIUI 12.5). Using 0.0.7 version.

**Comment by jayeshpansheriya** [comment]
@darmanovazamat can you please try to use latest version?

**Comment by jayeshpansheriya** [comment]
What you can do

Keep your current approach (preferred)

Works on stock Android and most OEMs.

Does not require READ_CONTACTS permission in manifest.

Optional fallback (for Samsung and strict OEMs)

Check if the query fails with a SecurityException.

If yes → gracefully return an error to Flutter and instruct the app to request READ_CONTACTS.

This way you don’t always ask for the permission, only on devices that misbehave.
